apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"   # after namespaces (-1), sealed-secrets (-1), orders-api (1)
spec:
  project: default
  source:
    repoURL: https://github.com/pankajmanik43/sre-platform-assessment.git
    targetRevision: main
    path: manifests/sre-agent
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sre-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
