apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-healthcheck
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"   # after the temporal frontend (2) is available
spec:
  project: default
  source:
    repoURL: https://github.com/pankajmanik43/sre-platform-assessment.git
    targetRevision: main
    path: manifests/temporal-healthcheck
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
