apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orders-api
  namespace: apps
  labels:
    app.kubernetes.io/name: orders-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-api
